export enum Roles {
    ADMIN = 'ADMIN',
    MANAGER = 'MANAGER',
    MANDOOB = 'MANDOOB',
    RATING = 'RATING',
    SEGELAT = 'SEGELAT',
    PHOTOGRAPHER = 'PHOTOGRAPHER',
    MEDICAL = 'MEDICAL',
    CARD = 'CARD',
    GATE = 'GATE',
    ANYUSER = 'ANYUSER'
}